---
name: build-metaprotocol

on:
  workflow_dispatch:
  push:
    branches:
    - "main"
    - "master"
    - "release/v*"
    paths-ignore:
    - "**/*.md"
    - "**/*.png"
  pull_request:
    branches:
    - "main"
    - "master"
    - "release/v*"
    paths-ignore:
    - "**/*.md"
    - "**/*.png"

concurrency: ci-${{ github.ref }}

jobs:
  BuildMetaProtocolBinary:
    runs-on: self-hosted
    timeout-minutes: 1440 # 12 hours
    strategy:
      fail-fast: true
      matrix:
        protocal: [dubbo]
    name: Build MetaProtocolProxy
    env:
      LOG_DIR: /tmp/test_logs
      LOG_PATH: /tmp/test_logs/${{ matrix.protocal }}.log
    steps:
      - name: Clean
        run: |
         sudo rm -rf /home/ubuntu/.cache/bazel
      - name: Checkout
        uses: actions/checkout@v4
      - name: install dependency
        run: |
          ./bazel/setup_clang.sh /home/ubuntu/clang+llvm-10.0.0-linux-gnu
      - name: Build
        run: |
          make build
      - name: setup hosts
        env: 
          DNS_NAME_FOR_DUBBO: 127.0.0.1 org.apache.dubbo.samples.basic.api.demoservice
        if: ${{ matrix.protocal == 'dubbo' }}
        run: |
          if [ `grep -c "$DNS_NAME_FOR_DUBBO" /etc/hosts` -eq 0 ];then
            sudo echo "$DNS_NAME_FOR_DUBBO" | sudo tee -a /etc/hosts
            cat /etc/hosts
          fi
      - name: run test
        shell: bash -x -eo pipefail {0}
        run: |
          mkdir $LOG_DIR || true
          sudo bash ${GITHUB_WORKSPACE}/test/${{ matrix.protocal }}/test.sh > $LOG_PATH 2>&1 &
          echo $! > $LOG_DIR/cmd.pid
          sleep 60
      - name: check result
        env: 
          EXPECT_LOG: Hello Aeraki, response from
        shell: bash -x -eo pipefail {0}
        run: |
          grep "$EXPECT_LOG" $LOG_PATH
          lines=`grep -c "$EXPECT_LOG" $LOG_PATH`
          echo "find right text lines: $lines"
          [ $lines -gt 0 ] && echo "assert ${{ matrix.protocal }} pass!!!"
      - name: debug with ssh
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 20
        
